name: Doc Deploy to GitHub Pages

on:
  push:
    branches:
      - dev

defaults:
  run:
    shell: bash
    working-directory: docs

jobs:
  deploy:
    name: Doc Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install
      - name: Build website
        run: yarn build

      - name: Doc Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
